### PR TITLE
Add tox env for building docs

### PR DESCRIPTION
**Pull request by jmbowman**
Add a tox environment for building the docs, and update the README to recommend tox for running tests.  This should wrap up all of the changes originally proposed in #20 .

This is about the end of the changes I was planning to make in the near future.  Any thoughts on when to make a new release?  I need to make some updates to [bok-choy](https://github.com/edx/bok-choy), and would rather not switch it over to installing needle from git.

### CODE REVIEW

**Comment by jphalip** [comment]
Thanks. Does that mean that the ReadTheDocs configuration also needs updating? By the way, I don't have access to the RTD project myself, so I'll have to check with Ben. Also, I've just noticed that the builds have been failing there for a while.... https://readthedocs.org/projects/needle/builds/

**Comment by jphalip** [comment]
Also, to answer you question, I should be able to push a new release in the coming days. I'm just hoping to resolve the RTD issue first.

**Comment by jmbowman** [comment]
It looks like your RTD build is configured to use a virtualenv with dependencies specified in a `requirements.txt` file at the project root, but you have no such file.  You can either fix that by adding such a file containing at least "Sphinx", or by changing the build config to not specify a requirements file (RTD installs a relatively recent version of Sphinx for builds by default).  I usually use a `requirements/docs.txt` file for my projects and pin known-working versions of all of Sphinx and all of its dependencies, but that's arguably overkill.

**Comment by jphalip** [comment]
That makes sense, thanks. I'll try to fix all of that soon and then I'll merge this PR.

**Comment by jphalip** [comment]
Cool, so I added a `docs/requirements.txt` file and the build passed. Merging now, thank you!

**Pull request merged**
